version: '3.9'

services:
  app:
    container_name: intercup-backend
    build: ./
    ports: 
      - 4000:4000
    environment:
      PORT: $PORT
      MONGODB: $MONGODB
      JWT_SECRET: $JWT_SECRET
      NODE_ENV: $NODE_ENV
      EMAIL_PORT: $EMAIL_PORT
      HOST: $HOST
      USER: $USER
      PASS: $PASS
      SERVICE: $SERVICE
      SECURE: $SECURE
      BASE_URL: $BASE_URL